#!/bin/bash

# Facebook Client Token Setup Guide
# App ID: 1187404556173198

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         GET FACEBOOK CLIENT TOKEN                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Your Facebook App ID: 1187404556173198"
echo ""
echo "📋 STEPS TO GET YOUR CLIENT TOKEN:"
echo ""
echo "1. Go to: https://developers.facebook.com/apps/1187404556173198/settings/basic/"
echo ""
echo "2. Scroll down to find 'Client Token' section"
echo ""
echo "3. Copy the Client Token (it will be a long string of letters and numbers)"
echo ""
echo "4. Run this command to update Info.plist:"
echo ""
echo "   cd /Users/kinjalkoli/TwinTale/TwinTale"
echo "   sed -i '' 's/YOUR_CLIENT_TOKEN/<paste-your-client-token-here>/g' Info.plist"
echo ""
echo "   (Replace <paste-your-client-token-here> with your actual token)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ ALREADY CONFIGURED:"
echo "   • Facebook App ID: 1187404556173198"
echo "   • URL Scheme: fb1187404556173198"
echo "   • Display Name: TwinTale"
echo ""
echo "⏳ STILL NEEDED:"
echo "   • Client Token (follow steps above)"
echo ""
